[package]
name = "Edelweiss"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
async-trait = "0.1.88"
libc = "0.2.172"

[features]
default = ["linux_bpf"]
android_bpf = []
linux_bpf = []